version: "3.8"

volumes:
  postgresql:
  q2tg:
  cache:

services:
  # 如果有现成的 Postgresql 实例，可以删除这一小节
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql:/var/lib/postgresql/data
      
  tunnel: #如果没有使用 Cloudflare Tunnel 暴露内网端口，可以删除这一小节
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN= #此处填入设定Cloudflare Tunnel时产生的指令的 --token 后面那一串密钥

  sign:
    image: xzhouqd/qsign:core-1.1.9
    restart: unless-stopped
    environment:
      # 需要与下方的 SIGN_VER 同步
      # 配置请参考 https://hub.docker.com/r/xzhouqd/qsign
      - BASE_PATH=/srv/qsign/qsign/txlib/8.9.71

  q2tg:
    image: ghcr.io/clansty/q2tg:sleepyfox
    restart: unless-stopped
    depends_on:
      - postgres
      - sign
    ports:
      # 如果要使用 RICH_HEADER 需要将端口发布到公网
      - 8080:8080
    volumes:
      - q2tg:/app/data
      # 下面这行是固定的，和你用不用 NapCat 没关系，不要动
      - cache:/root/.config/QQ/NapCat/temp
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TG_API_ID=
      - TG_API_HASH=
      - TG_BOT_TOKEN=
      - DATABASE_URL=postgres://user:password@postgres/db_name
      - SIGN_API=http://sign:8080/sign?key=114514
      - SIGN_VER=8.9.71 # 与上方 sign 容器的配置同步
      - TG_CONNECTION=tcp # 连接 Telegram 的方式，也可以改成 websocket
      # 如果你需要使用 /flags set RICH_HEADER 来显示头像，或者正确显示合并转发的消息记录，则需将 q2tg 8080 端口发布到公网，可以使用 cloudflare tunnel
      # 请尽量配置这个服务
      - WEB_ENDPOINT= # https://yourichheader.com 填写你发布到公网的域名
      #- CRV_VIEWER_APP=
      # DEPRECATED: 请使用 WEB_ENDPOINT
      #- CRV_API=
      #- CRV_KEY=
      # 要关闭文件上传提示，请取消注释以下变量 https://github.com/clansty/Q2TG/issues/153
      #- DISABLE_FILE_UPLOAD_TIP=1
      # 如果需要通过代理联网，那么设置下面两个变量
      #- PROXY_IP=
      #- PROXY_PORT=
      # 代理联网认证，有需要请修改下面两个变量
      #- PROXY_USERNAME=
      #- PROXY_PASSWORD=
